name: Packages

# » TODO:
#  › implement build summeries with 'push' event

on:
  # i'm having a hard time here, i'll implement it later
  #  push:
  #    branches:
  #      - main
  #    paths:
  #      - 'packages/**'
  workflow_dispatch:
    inputs:
      packages:
        description: 'A space-separated packages name to build.'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building for ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@master
        with:
          branch: edge
          arch: ${{ matrix.arch }}
          packages: >
            alpine-sdk
            abuild
            bash
            sudo

      - name: Setup and gather build summaries
        run: |
          mkdir artifacts
          if [[ '${{ github.event_name }}' = 'workflow_dispatch' ]]; then
            read -r -a packages <<<"${{ inputs.packages }}"
            for pkg in "${packages[@]}"; do
              [[ -d "./packages/$pkg" ]] || {
                echo "Not a package: $pkg"
                exit 1
              }
              tee -a packages.txt <<<"$pkg"
            done
          fi

      - name: Setup abuild
        shell: alpine.sh {0}
        env:
          ABUILD_PRIVKEY: ${{ secrets.ABUILD_PRIVKEY }}
        run: |
          echo "$ABUILD_PRIVKEY" >apk-repo.rsa
          mkdir -p ~/.abuild
          echo "PACKAGER_PRIVKEY='$PWD/apk-repo.rsa'" >"$HOME/.abuild/abuild.conf"
          sudo cp apk-repo.rsa.pub /etc/apk/keys

      - name: Build package
        shell: alpine.sh {0}
        run: |
          ./bake buildpkg $(cat packages.txt)
          ls -a
